Reset repository, packaging code as CommonJS only

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,33 +3,27 @@
 # Check if this is the initial commit
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-    against=HEAD
+  against=HEAD
 else
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # Use git diff-index to check for whitespace errors
-if ! git diff-index --check --cached $against
+if ! git diff-index --check --cached $against -- ':!*.js.snap' .
 then
-    echo "Aborting commit due to whitespace errors."
-    exit 1
-else
-    # Fail on first line that fails.
-    set -e
+  echo "Aborting commit due to whitespace errors."
+  exit 1
+fi
 
-    NEW_FILES=$(git --no-pager diff --name-only --cached)
-    JS_FILES=$(echo "$NEW_FILES" | { grep *.js || true; })
+# Only keep staged files that are added (A), copied (C) or modified (M).
+STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
+# Files which are only partly staged (eg. git add --patch).
+PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
+# Files which are fully staged.
+FULLY_STAGED=$(comm -23 <(echo "$STAGED") <(echo "$PATCH_STAGED"))
 
-    if [ -n "$JS_FILES" ];
-    then
-        npm run linter:js -s -- $JS_FILES
-    fi
-
-    # To test if there are changes to Sass files as well (not useful at the moment):
-    # if [ -n "$JS_FILES" ] || [ -n "$SASS_FILES" ];
-    if [ -n "$JS_FILES" ];
-    then
-        npm run test -s;
-        exit 0
-    fi
+if [ -n "$JS_STAGED" ];
+then
+  # npx eslint $JS_STAGED
+  npm run test
 fi
